USE enrollment;

CREATE TABLE IF NOT EXISTS `enrollment`.`MEMBER_MASTER` (
 `SEQ_MEMB_ID` int NOT NULL AUTO_INCREMENT,
 `SUBSCRIBER_ID` VARCHAR(50) NOT NULL,
 `PERSON_NUMBER` CHAR(2) NOT NULL,
 `LAST_NAME` VARCHAR(60) NOT NULL,
 `FIRST_NAME` VARCHAR(30),
 `DATE_OF_BIRTH` DATE NOT NULL,
 `ELIG_STAT` VARCHAR(1) NOT NULL,
PRIMARY KEY (`SEQ_MEMB_ID`,`SUBSCRIBER_ID`),
INDEX `IDX_SEQ_MEMB_ID` (`SEQ_MEMB_ID` ASC),
INDEX `IDX_SUBSCRIBER_ID` (`SUBSCRIBER_ID` ASC)
);

ALTER TABLE `enrollment`.`MEMBER_MASTER` AUTO_INCREMENT = 2000;


CREATE TABLE IF NOT EXISTS `enrollment`.`MEMBER_ADDRESS` (
 `SEQ_MEMB_ADDRESS` int NOT NULL AUTO_INCREMENT,
 `SEQ_MEMB_ID` int NOT NULL,
 `HOME_PHONE_NUMBER` VARCHAR(50) NOT NULL,
 PRIMARY KEY (`SEQ_MEMB_ADDRESS`),
INDEX `IDX_SEQ_MEMB_ID` (`SEQ_MEMB_ID` ASC),
CONSTRAINT `FK2_SEQ_MEMB_ID`
FOREIGN KEY (`SEQ_MEMB_ID`) REFERENCES `enrollment`.`member_master` (`SEQ_MEMB_ID`)  ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE `enrollment`.`MEMBER_ADDRESS` AUTO_INCREMENT = 2000;